apiVersion: 1
contactPoints:
    - orgId: 1
      name: Local webhook
      receivers:
        - uid: dfs2y3zyvvh8gd
          type: webhook
          settings:
            url: http://alert-receiver:8080/alerts
          disableResolveMessage: false
